name: LeetSyncMaster
on: 
  workflow_dispatch:
  schedule:
      - cron: '0 0 * * *'  # Run the workflow daily at midnight
jobs:
  leetcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Success Step 1 🤡"      
      - name: Run LeetSyncMaster
        uses: ./code
        with:
          GITHUB_TOKEN: ${{ github.token }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}